name = "Jelly Pack"
author = "enby"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b0919b391326363ae9e04b4f67053e192b3b1edc8974ef857c50d97dc83babb"

[versions]
minecraft = "1.19.1"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.19"]
